# Generated by Django 2.2.6 on 2020-05-12 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcontact',
            name='item',
        ),
    ]
