# Generated by Django 2.2.6 on 2020-05-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Como registrarte e inicio de sesión', 'Como registrarte e inicio de sesión'), ('Método de publicación / reglas de publicación', 'Método de publicación / reglas de publicación'), ('Probemas entre usuarios', 'Probemas entre usuarios'), ('Otros', 'Otros')], max_length=60)),
                ('email_address', models.EmailField(max_length=254)),
                ('content', models.TextField()),
            ],
        ),
    ]
