# Generated by Django 2.2.6 on 2020-05-10 03:30

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm0', models.CharField(choices=[('GUATEMALA', 'GUATEMALA'), ('OTROS', 'OTROS')], default='Guatemala', max_length=15)),
                ('adm1', models.CharField(max_length=15)),
                ('adm2', models.CharField(max_length=30)),
                ('description', models.TextField(default='Por favor escriba su auto presentación')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('image', models.ImageField(blank=True, default='default_profile.jpeg', null=True, upload_to='images/')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('sex', models.IntegerField(choices=[(0, 'NotSet'), (1, 'Hombre'), (2, 'Mujer')], default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
