# Generated by Django 2.2.6 on 2020-05-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='feedback',
            field=models.ManyToManyField(to='feedback.Feedback'),
        ),
    ]
