# Generated by Django 2.2.6 on 2020-05-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200521_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='radius',
            field=models.IntegerField(default=0),
        ),
    ]
