# Generated by Django 2.2.6 on 2020-05-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='feedback',
            field=models.ManyToManyField(blank=True, null=True, to='feedback.Feedback'),
        ),
    ]
