# Generated by Django 2.2.6 on 2020-05-10 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('checked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('aviso_user', models.ManyToManyField(null=True, to='profiles.Profile')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
        ),
    ]
