# Generated by Django 2.2.6 on 2020-05-12 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_feedback'),
        ('avisos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aviso',
            name='aviso_user',
        ),
        migrations.AddField(
            model_name='aviso',
            name='aviso_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.Profile'),
        ),
    ]
