# Generated by Django 2.2.6 on 2020-05-21 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicetoken',
            old_name='token',
            new_name='device_token',
        ),
    ]
