# Generated by Django 2.2.6 on 2020-05-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200521_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='device_token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
