# Generated by Django 2.2.6 on 2020-05-10 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='user',
            new_name='evaluator',
        ),
    ]
