# Generated by Django 2.2.6 on 2020-05-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20200510_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='level',
            field=models.IntegerField(choices=[(5, '満足'), (4, '良い'), (3, '普通'), (3, '不満'), (1, '悪い')]),
        ),
    ]
