# Generated by Django 2.2.6 on 2020-05-10 03:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('adm1_es', models.CharField(max_length=50)),
                ('adm1_pcode', models.CharField(max_length=50)),
                ('adm1_ref', models.CharField(max_length=50)),
                ('adm1alt1es', models.CharField(max_length=50)),
                ('adm1alt2es', models.CharField(max_length=50)),
                ('adm0_es', models.CharField(max_length=50)),
                ('adm0_pcode', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('validon', models.DateField()),
                ('validto', models.DateField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('adm2_es', models.CharField(max_length=50)),
                ('adm2_pcode', models.CharField(max_length=50)),
                ('adm2_ref', models.CharField(max_length=50)),
                ('adm2alt1es', models.CharField(max_length=50, null=True)),
                ('adm2alt2es', models.CharField(max_length=50, null=True)),
                ('adm1_es', models.CharField(max_length=50)),
                ('adm1_pcode', models.CharField(max_length=50)),
                ('adm0_es', models.CharField(max_length=50)),
                ('adm0_pcode', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('validon', models.DateField()),
                ('validto', models.DateField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Prefectura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('adm2_es', models.CharField(max_length=50)),
                ('adm2_pcode', models.CharField(max_length=50)),
                ('adm2_ref', models.CharField(max_length=50)),
                ('adm2alt1es', models.CharField(max_length=50, null=True)),
                ('adm2alt2es', models.CharField(max_length=50, null=True)),
                ('adm1_es', models.CharField(max_length=50)),
                ('adm1_pcode', models.CharField(max_length=50)),
                ('adm0_es', models.CharField(max_length=50)),
                ('adm0_pcode', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('validon', models.DateField()),
                ('validto', models.DateField(null=True)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='RegionClassed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prefecturas.Departamento')),
                ('municipios', models.ManyToManyField(to='prefecturas.Municipio')),
            ],
        ),
    ]
