# Generated by Django 2.2.6 on 2020-05-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_contacts', '0002_remove_itemcontact_item'),
        ('items', '0004_auto_20200511_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_contacts',
            field=models.ManyToManyField(to='item_contacts.ItemContact'),
        ),
    ]
