# Generated by Django 2.2.6 on 2020-05-15 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direct_messages', '0003_remove_directmessage_item'),
        ('items', '0006_item_solicitudes'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='direct_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='direct_messages.DirectMessage'),
        ),
    ]
