# Generated by Django 2.2.6 on 2020-06-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_auto_20200604_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='adm1',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='adm2',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
