# Generated by Django 2.2.6 on 2020-05-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Donar o vender', 'Donar o vender'), ('Buscar ayuda', 'Buscar ayuda'), ('Anunciate', 'Anunciate')], max_length=30, null=True)),
            ],
        ),
    ]
