# Generated by Django 2.2.6 on 2020-06-06 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_auto_20200606_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='number',
        ),
    ]
