# Generated by Django 2.2.3 on 2020-07-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_auto_20200606_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='number',
            field=models.CharField(choices=[('1', 'quiero donar o vender'), ('2', 'quiero buscar donante'), ('3', 'quiero avisar'), ('4', 'quiero buscar una habitación'), ('5', 'quiero alquilar una habitación'), ('6', 'quiero dar pensionado'), ('7', 'quiero buscar pensionista'), ('8', 'quiero buscar empleado'), ('9', 'quiero buscar trabajador'), ('10', 'publicidad de Enpresas y Servicios')], max_length=30, unique=True),
        ),
    ]
