# Generated by Django 2.2.6 on 2020-05-14 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='item',
        ),
    ]
