# Generated by Django 2.2.6 on 2020-05-10 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.Item')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner', to='profiles.Profile')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participant', to='profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='DirectMessageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='direct_messages.DirectMessage')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.Profile')),
            ],
        ),
    ]
