# Generated by Django 2.2.6 on 2020-05-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='is_feedbacked_by_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='is_feedbacked_by_participant',
            field=models.BooleanField(default=False),
        ),
    ]
