# Generated by Django 2.2.6 on 2020-05-14 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct_messages', '0002_auto_20200510_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directmessage',
            name='item',
        ),
    ]
